version: '3'
services:
    rembrandt:
        image: bptlab/rembrandt:latest
        ports:
            - 3000:3000
        environment:
            - MONGO_HOST=mongo
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - data-exchange:/usr/src/rembrandt/dataExchange
    mongo:
        image: mongo:latest
volumes:
    data-exchange:
