version: '3'
services:
    rembrandt:
        image: rembrandt:latest
        ports:
            - 3000:3000
        environment:
            - MONGO_HOST=mongo
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    mongo:
        image: mongo:latest
